### ISSUE TITLE
App Store icon

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/AmphibiaWebIOS#3]
We need App Store icon (see: This icon will be used on the App Store. For apps built with Xcode 9 or later, add this icon in the build. For apps built with earlier versions of Xcode, add the icon here. https://help.apple.com/itunes-connect/developer/#/dev8b5cb82e2)

Let's use the new logo as the App Store icon

**Comment by Chenyu-Shi** [comment]
That's already added. It should be in here: https://github.com/AmphibiaWeb/AmphibiaWebIOS/tree/master/AmphibiaWeb2/Media.xcassets/AppIcon.appiconset
Not sure which file it is but when you open it in xcode you can see the App Store Icon
