### ISSUE TITLE
Screenshots of updated app

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/AmphibiaWebIOS#4]
Post several screenshots of new app so we can submit our application to campus

**Comment by Chenyu-Shi** [comment]
See https://github.com/AmphibiaWeb/AmphibiaWebIOS/tree/master/Screenshots

**Comment by mkoo** [comment]
Please rename these to something descriptive (eg., screenshot_splashpage, screenshot_searchinterface, etc)

**Comment by Chenyu-Shi** [comment]
Done
